### PR TITLE
[WIP] added PowerVC miminal version requirement

### PR DESCRIPTION
**Pull request by iv1111**

### CODE REVIEW

**Comment by agrare** [comment]
@iv1111 is this a property that we can access via the API?  We can check this when we verify credentials and disallow earlier versions.

We should also add this to the documentation: https://github.com/ManageIQ/manageiq-documentation/blob/master/managing_providers/cloud_providers/_topics/adding_ibm_power_vc_providers.md

**Comment by iv1111** [comment]
@agrare Looks like as @jaywcarman has pointed out there is a way to get the PowerVC version via API. You can do a simple HTTP GET request with no credentials needed:  `curl -c GET 'https://<host>/powervc/version'`.

The question is where to put the corresp. code. We inherit most of the methods from OpenStack, which uses Fog SDK for access. I can't find any methods there in the SDK that would deliver the remote's release version.

Do you think it'd be ok to add a simple REST call for that in the PowerVC provider code? Alternatively, there is a bunch of handlers here: 
`manageiq-providers-openstack/lib/manageiq/providers/openstack/legacy/openstack_handle` where we could add our own handler for the PowerVC case but I'm not sure whether mixing OpenStack and PowerVC there would be a good idea.

**Comment by agrare** [comment]
Hey @iv1111 there are two places the API version would be helpful, one is part of inventory collection where you can set the provider's api_version.  You can add a method to your parser class that gets this and sets it to the `persister.ext_management_system` collection similar to what VMware does: https://github.com/ManageIQ/manageiq-providers-vmware/blob/master/app/models/manageiq/providers/vmware/infra_manager/inventory/parser.rb#L35-L40

The other (which is I think what you really care about) is when verifying the credentials, this way you can check for a minimum supported version and if the PowerVC system is too old you can fail the verify_credentials and the provider cannot be added.  You can override the `.verify_credentials` class method in the openstack cloud_manager, do a simple rest client GET and compare the version, then call super to let the OpenStack check continue.

**Comment by iv1111** [comment]
@agrare I've created a new PR here, closing this one.
https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/32

**Pull request closed without merging**
