### PR TITLE
restructured registration form & bugfix

### PR DESCRIPTION
**Pull request by iv1111**
- restructured registration form
- 1 bugfix in the template lookup

### CODE REVIEW

**Comment by iv1111** [comment]
Rubocop seems to be fine, codeclimate shows some internal error. Removing the WIP.

**Review by jaywcarman — APPROVED** [review]
LGTM

**Comment by iv1111** [comment]
> LGTM

Seems ok. Let's merge then.

**Comment by Fryguy** [comment]
Backported to `morphy` in commit 394e78a0f83294e38c2917fad882b1746bfbc848.

```text
commit 394e78a0f83294e38c2917fad882b1746bfbc848
Author: Jay Carman <jwcarman@us.ibm.com>
Date:   Thu Jun 24 07:54:13 2021 -0500

    Merge pull request #15 from iv1111/master
    
    restructured registration form & bugfix
    
    (cherry picked from commit 72008d6cde05e9f8d69a0db6a4bc7b201c0cfaab)
```

**Pull request merged**
