### PR TITLE
Prepare initial third party services

### PR DESCRIPTION
**Pull request by Fryguy**
Prepare initial third party services

Part of #9

### CODE REVIEW

**Comment by Fryguy** [comment]
@agrare Please review.

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
@Fryguy A conflict occurred during the backport of this pull request to `morphy`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `morphy` branch in order to resolve this.

Conflict details:

```diff
diff --cc README.md
index 35158c7,8b34b48..0000000
--- a/README.md
+++ b/README.md
@@@ -1,12 -1,12 +1,20 @@@
  # ManageIQ::Providers::IbmPowerVc
  
++<<<<<<< HEAD
 +[![Build Status](https://travis-ci.com/ManageIQ/manageiq-providers-ibm_power_vc.svg?branch=morphy)](https://travis-ci.com/ManageIQ/manageiq-providers-ibm_power_vc)
 +[![Maintainability](https://api.codeclimate.com/v1/badges/<badge_token>/maintainability)](https://codeclimate.com/github/ManageIQ/manageiq-providers-ibm_power_vc/maintainability)
 +[![Test Coverage](https://api.codeclimate.com/v1/badges/<badge_token>/test_coverage)](https://codeclimate.com/github/ManageIQ/manageiq-providers-ibm_power_vc/test_coverage)
 +[![Security](https://hakiri.io/github/ManageIQ/manageiq-providers-ibm_power_vc/morphy.svg)](https://hakiri.io/github/ManageIQ/manageiq-providers-ibm_power_vc/morphy)
 +
++=======
+ [![Build Status](https://travis-ci.com/ManageIQ/manageiq-providers-ibm_power_vc.svg?branch=master)](https://travis-ci.com/ManageIQ/manageiq-providers-ibm_power_vc)
+ [![Maintainability](https://api.codeclimate.com/v1/badges/ca08315939e0235081cb/maintainability)](https://codeclimate.com/github/ManageIQ/manageiq-providers-ibm_power_vc/maintainability)
+ [![Test Coverage](https://api.codeclimate.com/v1/badges/ca08315939e0235081cb/test_coverage)](https://codeclimate.com/github/ManageIQ/manageiq-providers-ibm_power_vc/test_coverage)
+ [![Security](https://hakiri.io/github/ManageIQ/manageiq-providers-ibm_power_vc/master.svg)](https://hakiri.io/github/ManageIQ/manageiq-providers-ibm_power_vc/master)
++>>>>>>> 42ec0b1... Merge pull request #12 from Fryguy/new_plugin_repo
  [![Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/ManageIQ/manageiq-providers-ibm_power_vc?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
  
+ 
  ManageIQ plugin for the [IBM PowerVC](https://www.ibm.com/products/powervc) provider.
  
  ## Development
```

**Comment by agrare** [comment]
Morphy backport https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/23

**Comment by Fryguy** [comment]
Backported to `morphy` via https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/23

**Pull request merged**
